name: CI/CD for data package

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
            python-version: 3.9
      - name: Install dependencies
        run: python -m pip install -r requirements.txt --upgrade pip
      - run: frictionless validate datapackage.json
  publish:
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
            python-version: 3.9
      - name: Install dependencies
        run: python -m pip install -r requirements.txt --upgrade pip
      - name: Publish data package to CKAN with dpckan
        env:
            CKAN_KEY: ${{ secrets.CKAN_KEY }} 
        run: dpckan resource update --ckan-host https://homologa.cge.mg.gov.br/ --ckan-key "$CKAN_KEY" --resource-name estados --resource-id cefb9e7e-bfa3-4677-bacc-ad6c6c5fadb1
